### ISSUE TITLE
App won't start with in absence of internet connectivity. Even if cache is enabled.

### ISSUE THREAD

**Issue by sscarduzio** [envkey/envkey#20] opened 2022-06-09 15:44 UTC
**OS**: MacOS Monterey 12.4
**Envkey Version**:  ENVKEY_SOURCE_VERSION = "2.0.22"

```python
print("EK Should cache? " + os.environ.get("ENVKEY_SHOULD_CACHE"))
import envkey
secrets = envkey.fetch_env(cache_enabled=True)
print("..Done!")
```
With WiFi on, this works ok.
With WiFi off, it hangs after the first print.

A few issues with this:
 
1. Notice how my `import envkey` is unnaturally after the first print. I had to move it down, otherwise the `import envkey` hangs on network. This completely invalidates the presence of `cache_enabled=True` as `fetch_env` function argument.

2. Envkey should detect no network interface is up, and immediately fallback to loading from `~/.envkey/cache/xxxxx` file (which in turn, is correctly updated according to filesystem timestamps). 

3. Even if the network was up, but dropping packets, a **configurable timeout** should be applied before falling back to cache.

**Comment by danenania** [comment] 2022-06-09 20:28
Looking into this. There's a fairly long timeout and a number of retries before falling back to cache in order to handle patchy network conditions (the timeout is configurable when using envkey-source directly but not via language libraries). It would definitely be good to revert to the cache immediately when there's no network interface.

**Comment by danenania** [comment] 2022-06-09 23:56
Hey @sscarduzio I've tried this a bunch of different ways and am unable to reproduce. I'm seeing immediate results from cache with wifi off, at least on Monterey 12.1. I can try upgrading to see if there's some difference in 12.4 but it seems unlikely.

One thing to confirm: for caching to work, you have to first load an `ENVKEY` successfully with caching enabled (with wifi on). Perhaps you ran your example before first loading that `ENVKEY` successfully?

**Comment by sscarduzio** [comment] 2022-06-10 09:47
OK I got to the bottom of this: it was [Tailscale](https://tailscale.com/). 

It creates its own interface, and it stays open even when you are disconnected. The TCP stack in my machine believed it was connected because of that.

Go figure. Thanks for your investigation anyways @danenania!


Anyways, one of my initial observations remains valid: why `import envkey` already loads all variables? This is a blocking operation that freezes all the app, shouldn't we effectively load the variables when `fetch_env` is called (honoring the caching option)?

**Comment by danenania** [comment] 2022-06-10 20:57
Ok, I'm glad to hear you got to the bottom of it!

I think it _should_ still timeout eventually but it would take awhile with the high default timeouts and all the retries--so it could seem like it's just hanging. That said, if it's really just hanging forever then that's a bug that should be fixed. 

I'll close this for now but if you confirm it's hanging forever under these conditions then I can re-open or make a new issue to fix that.

> Anyways, one of my initial observations remains valid: why import envkey already loads all variables? This is a blocking operation that freezes all the app, shouldn't we effectively load the variables when fetch_env is called (honoring the caching option)?

For this you can set `ENVKEY_DISABLE_AUTOLOAD=1` to prevent loading on import.

**Closed by danenania** 2022-06-10 20:57 UTC

**Comment by sscarduzio** [comment] 2022-06-12 20:54
Hi @danenania, thanks for the hint about `ENVKEY_DISABLE_AUTOLOAD`, this is very helpful!

BTW I could reproduce the hang for a long time issue without depending on Tailscale, and measure how long it hangs (~4 minutes).

The long timeout happens in general when the default gateway drops packets.

To reproduce this on MacOS: 
- delete the default route
- add a new default route to an IP that does not forward packets anywhere

```
$ sudo route delete default
$ sudo route add default 100.98.241.119
```

At this point if you run this Python code:

```python

from time import time

t1 = time()
print("loading envkey...")
try:
    import envkey
except Exception as e:
    print(str(e))
t2 = time()
print(f'⏰ loaded in {(t2 - t1):.4f} seconds')

```

You eventually get this error:
```
loading envkey...
ENVKEY invalid. Couldn't load vars.
⏰ loaded in 245.0167 seconds
envkey-source echo 'error: could not load from server.
fetch error: Get "https://api-v2-2.envkey.com/fetch?fetchServiceVersion=2&envkeyIdPart=<redacted>&clientName=envkey-source&clientVersion=2.0.22&clientOs=darwin&clientArch=arm64": context deadline exceeded (Client.Timeout exceeded while awaiting headers)'; false


Process finished with exit code 0
```

I hope this is helpful.

**Comment by danenania** [comment] 2022-06-12 22:47
Thanks @sscarduzio that sounds about right given multiple failovers and retries with exponential backoff though obviously it does also seem too long for a dev situation--it might be reasonable on a server when there's no cache to fall back to, but it should probably fail sooner than that and revert to the cache when caching is enabled.
