### ISSUE TITLE
apicommunity release 2.3 don’t work

### ISSUE THREAD

**Issue by ldidry** [envkey/envkey#86] opened 2023-09-04 09:48 UTC
I noticed two problems:
- the sign-up token is always invalid:
```
2023-09-04T11:18:45.621837+02:00 server envkey-api[487878]: {"ts":"2023-09-04T09:18:45.621Z","proc":"main","msg":"api error: email token invalid","status":401,"stack":"Error: email token invalid\n    at Object.handler (/tmp/webpack:/Users/daneschneider/projects/envkey/v2/public/app/api/shared/src/api_handlers/email_verifications.ts:190:13)\n    at process.skipLogging (node:internal/process/task_queues:96:5)\n    at res (/tmp/webpack:/Users/daneschneider/projects/envkey/v2/public/app/api/shared/src/handler.ts:866:9)\n    at Object.t.tryHandleAction (/tmp/webpack:/Users/daneschneider/projects/envkey/v2/public/app/api/shared/src/handler.ts:500:13)\n    at Object.t.handleAction (/tmp/webpack:/Users/daneschneider/projects/envkey/v2/public/app/api/shared/src/handler.ts:227:7)","elapsed":"5ms"}
```
- the invitation don’t work either:
```
2023-09-04T10:46:38.969682+02:00 jimbo envkey-api[484712]: {"ts":"2023-09-04T08:46:38.969Z","proc":"main","msg":"api error: not found","status":404,"stack":"Error: not found\n    at Object.t.authenticate (/tmp/webpack:/Users/daneschneider/projects/envkey/v2/public/app/api/shared/src/auth.ts:123:17)\n    at process.auth (node:internal/process/task_queues:96:5)\n    at Object.t.handleAction (/tmp/webpack:/Users/daneschneider/projects/envkey/v2/public/app/api/shared/src/handler.ts:147:9)","elapsed":"6ms"}
```

I used the 2.1.4 release to be able to sign-up, then upgraded the server and invite a coworker, who couldn’t join the organization.
I retried the whole process (sign-up, then invite) with 2.1.4 release and it works well.

I did my first tests last week and I don’t remember if I tested one of the 2.2.x releases too.

**Comment by danenania** [comment] 2024-01-03 18:04
Closing for now as we haven't been able to reproduce this one. Are you still having this issue?

**Closed by danenania** 2024-01-03 18:04 UTC

**Comment by ldidry** [comment] 2024-01-08 10:55
I’ll test 2.3.6 as soon as possible.

**Comment by ldidry** [comment] 2024-01-10 14:32
I upgraded to 2.3.6 and it still fails.
I got a better error log, though:
```
janv. 10 15:28:44 jimbo envkey-api[52236]: {"ts":"2024-01-10T14:28:44.888Z","proc":"main","msg":"Transaction error:","alert":true,"err":{"message":"You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'AS put ON DUPLICATE KEY UPDATE fullKey = put.fullKey, body = put.body, data =...' at line 1", "code":"ER_PARSE_ERROR","errno":1064,"sqlState":"42000","sqlMessage":"You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'AS put ON DUPLICATE KEY UPDATE fullKey = put.fullKey, body = put.body, data =...' at line 1","name":"Error","stack":"Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'AS put ON DUPLICATE KEY UPDATE fullKey = put.fullKey, body = put.body, data =...' at line 1
    at c.query (/tmp/webpack:/Users/daneschneider/projects/envkey/v2/node_modules/mysql2/promise.js:92:22)
    at Object.execQuery (/tmp/webpack:/Users/daneschneider/projects/envkey/v2/public/app/api/shared/src/db_fns.ts:69:30)
    at Object.executeTransactionStatements (/tmp/webpack:/Users/daneschneider/projects/envkey/v2/public/app/api/shared/src/db_fns.ts:778:12)
    at Object.executeTransactionStatements (/tmp/webpack:/Users/daneschneider/projects/envkey/v2/public/app/api/shared/src/db.ts:189:15)
    at execTransaction (/tmp/webpack:/Users/daneschneider/projects/envkey/v2/public/app/api/shared/src/handler.ts:618:15)
    at Object.t.tryHandleAction (/tmp/webpack:/Users/daneschneider/projects/envkey/v2/public/app/api/shared/src/handler.ts:662:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Object.t.handleAction (/tmp/webpack:/Users/daneschneider/projects/envkey/v2/public/app/api/shared/src/handler.ts:233:7)"},"stack":"Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'AS put ON DUPLICATE KEY UPDATE fullKey = put.fullKey, body = put.body, data =...' at line 1
    at c.query (/tmp/webpack:/Users/daneschneider/projects/envkey/v2/node_modules/mysql2/promise.js:92:22)
    at Object.execQuery (/tmp/webpack:/Users/daneschneider/projects/envkey/v2/public/app/api/shared/src/db_fns.ts:69:30)
    at Object.executeTransactionStatements (/tmp/webpack:/Users/daneschneider/projects/envkey/v2/public/app/api/shared/src/db_fns.ts:778:12)
    at Object.executeTransactionStatements (/tmp/webpack:/Users/daneschneider/projects/envkey/v2/public/app/api/shared/src/db.ts:189:15)
    at execTransaction (/tmp/webpack:/Users/daneschneider/projects/envkey/v2/public/app/api/shared/src/handler.ts:618:15)
    at Object.t.tryHandleAction (/tmp/webpack:/Users/daneschneider/projects/envkey/v2/public/app/api/shared/src/handler.ts:662:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Object.t.handleAction (/tmp/webpack:/Users/daneschneider/projects/envkey/v2/public/app/api/shared/src/handler.ts:233:7)"}
```

My database is MariaDB on Debian 12
```
mariadb --version
mariadb  Ver 15.1 Distrib 10.11.4-MariaDB, for debian-linux-gnu (x86_64) using  EditLine wrapper
```

**Comment by danenania** [comment] 2024-01-10 14:51
@ldidry It looks like you may not be using a compatible DB. EnvKey requires MySQL 8.

**Comment by ldidry** [comment] 2024-01-10 15:09
Ok, thx.

**Comment by ldidry** [comment] 2024-01-11 10:07
I confirm that using MySQL 8 makes it work. Thank you 🙂

I guess that you’re unlikely to support PostgreSQL in the future?

**Comment by danenania** [comment] 2024-01-11 13:42
We've been happy enough with MySQL for our own purposes so it's not something we're likely to prioritize, but I'd be willing to offer support if a contributor wants to take it on. There's a thread on it here: https://github.com/envkey/envkey/discussions/101

**Comment by ldidry** [comment] 2024-01-11 15:28
Thx for the link 🙂
